/* This file has been automatically generated by RPC-Generator
   https://github.com/Crystal-Photonics/RPC-Generator
   You should not modify this file manually. */

#ifndef RPC_TYPES_H
#define RPC_TYPES_H

#include <stddef.h>

typedef enum{
        RPC_SUCCESS,
        RPC_FAILURE,
        RPC_COMMAND_UNKNOWN,
        RPC_COMMAND_INCOMPLETE
    } RPC_RESULT;
    
typedef struct {
	RPC_RESULT result;
	size_t size;
} RPC_SIZE_RESULT;

typedef enum {
    RPC_mutex_parsing_complete,
    RPC_mutex_caller,
    RPC_mutex_in_caller,
    RPC_mutex_answer,
    RPC_MUTEX_COUNT
} RPC_mutex_id;
#define RPC_number_of_mutexes 4

#endif /* RPC_TYPES_H */
