/* This file has been automatically generated by RPC-Generator
   https://github.com/Crystal-Photonics/RPC-Generator
   You should not modify this file manually. */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "..\..\..\include\rpc_transmission\server\generated_general\RPC_TRANSMISSION_network.h"
#include "..\..\..\include\rpc_transmission\server\generated_general\RPC_TRANSMISSION_parser.h"	

/* Receives a pointer to a (partly) received message and it's size.
   Returns a result and a size. If size equals RPC_TRANSMISSION_SUCCESS then size is the
   size that the message is supposed to have. If result equals RPC_TRANSMISSION_COMMAND_INCOMPLETE
   then more bytes are required to determine the size of the message. In this case
   size is the expected number of bytes required to determine the correct size.*/
RPC_SIZE_RESULT RPC_TRANSMISSION_get_request_size(const void *buffer, size_t size_bytes){
	const unsigned char *current = (const unsigned char *)buffer;
	RPC_SIZE_RESULT returnvalue;

	if (size_bytes == 0){
		returnvalue.result = RPC_COMMAND_INCOMPLETE;
		returnvalue.size = 1;
		return returnvalue;
	}

	if((*current) & 1){
		returnvalue.size = 0;
		returnvalue.result = RPC_COMMAND_UNKNOWN;
		return returnvalue;
	}else{

		returnvalue.size = *current;

	}

	returnvalue.result = returnvalue.size > size_bytes ? RPC_COMMAND_INCOMPLETE : RPC_SUCCESS;
	return returnvalue;
}



#ifdef __cplusplus
}
#endif /* __cplusplus */
